import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';
import { Trip, DayPlan } from '@/types';

export async function exportToPDF(trip: Trip): Promise<void> {
  try {
    const pdf = new jsPDF('p', 'mm', 'a4');
    const pageWidth = pdf.internal.pageSize.getWidth();
    const pageHeight = pdf.internal.pageSize.getHeight();
    const margin = 20;
    let yPosition = margin;

    // Helper function to add new page if needed
    const checkPageBreak = (requiredHeight: number) => {
      if (yPosition + requiredHeight > pageHeight - margin) {
        pdf.addPage();
        yPosition = margin;
      }
    };

    // Title Page
    pdf.setFontSize(24);
    pdf.setFont('helvetica', 'bold');
    pdf.text('UAE Tour Planner Itinerary', pageWidth / 2, yPosition, { align: 'center' });
    yPosition += 15;

    pdf.setFontSize(16);
    pdf.setFont('helvetica', 'normal');
    pdf.text(trip.name, pageWidth / 2, yPosition, { align: 'center' });
    yPosition += 10;

    pdf.setFontSize(12);
    pdf.text(`${trip.onboardingData.adults + trip.onboardingData.children} Travelers • ${trip.days.length} Days`, pageWidth / 2, yPosition, { align: 'center' });
    yPosition += 10;
    
    pdf.text(`Total Budget: $${trip.totalCostUSD.toLocaleString()}`, pageWidth / 2, yPosition, { align: 'center' });
    yPosition += 20;

    // Trip Summary
    pdf.setFontSize(14);
    pdf.setFont('helvetica', 'bold');
    pdf.text('Trip Summary', margin, yPosition);
    yPosition += 10;

    pdf.setFontSize(11);
    pdf.setFont('helvetica', 'normal');
    const summaryLines = [
      `Cities: ${trip.onboardingData.cities.map(city => city.charAt(0).toUpperCase() + city.slice(1)).join(', ')}`,
      `Dates: ${new Date(trip.onboardingData.startDate).toLocaleDateString()} - ${new Date(trip.onboardingData.endDate).toLocaleDateString()}`,
      `Budget: $${trip.onboardingData.budgetUSD.toLocaleString()}`,
      `Pace: ${trip.onboardingData.pace.charAt(0).toUpperCase() + trip.onboardingData.pace.slice(1)}`,
      `Interests: ${trip.onboardingData.interests.map(interest => interest.charAt(0).toUpperCase() + interest.slice(1)).join(', ')}`
    ];

    summaryLines.forEach(line => {
      checkPageBreak(8);
      pdf.text(line, margin, yPosition);
      yPosition += 8;
    });

    yPosition += 15;

    // Daily Itinerary
    trip.days.forEach((day, dayIndex) => {
      checkPageBreak(40);
      
      // Day header
      pdf.setFontSize(16);
      pdf.setFont('helvetica', 'bold');
      pdf.text(`Day ${day.dayNumber} - ${day.city.charAt(0).toUpperCase() + day.city.slice(1)}`, margin, yPosition);
      yPosition += 8;

      pdf.setFontSize(12);
      pdf.setFont('helvetica', 'normal');
      pdf.text(new Date(day.date).toLocaleDateString('en-US', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' }), margin, yPosition);
      yPosition += 8;

      pdf.text(`Daily Cost: $${day.dailyCostUSD.toLocaleString()}`, margin, yPosition);
      yPosition += 15;

      // Activities
      day.activities.forEach((activity, activityIndex) => {
        checkPageBreak(25);
        
        pdf.setFontSize(12);
        pdf.setFont('helvetica', 'bold');
        pdf.text(`${activityIndex + 1}. ${activity.name}`, margin + 5, yPosition);
        yPosition += 8;

        pdf.setFontSize(10);
        pdf.setFont('helvetica', 'normal');
        
        // Activity details
        const details = [
          `Duration: ${activity.durationHours} hours`,
          `Cost: $${activity.estimatedCostUSD}`,
          `Best time: ${activity.timeOfDay.charAt(0).toUpperCase() + activity.timeOfDay.slice(1)}`,
          `Family friendly: ${activity.familyFriendly ? 'Yes' : 'No'}`
        ];

        details.forEach(detail => {
          pdf.text(detail, margin + 10, yPosition);
          yPosition += 6;
        });

        // Description (word wrap)
        const description = activity.description;
        const lines = pdf.splitTextToSize(description, pageWidth - margin * 2 - 15);
        lines.forEach((line: string) => {
          checkPageBreak(6);
          pdf.text(line, margin + 10, yPosition);
          yPosition += 6;
        });

        yPosition += 8;
      });

      yPosition += 10;

      // Add page break between days (except last day)
      if (dayIndex < trip.days.length - 1) {
        checkPageBreak(20);
      }
    });

    // Footer on each page
    const totalPages = pdf.internal.getNumberOfPages();
    for (let i = 1; i <= totalPages; i++) {
      pdf.setPage(i);
      pdf.setFontSize(8);
      pdf.setFont('helvetica', 'italic');
      pdf.text(`Page ${i} of ${totalPages}`, pageWidth / 2, pageHeight - 10, { align: 'center' });
      pdf.text('Generated by UAE Tour Planner', pageWidth / 2, pageHeight - 5, { align: 'center' });
    }

    // Save the PDF
    const fileName = `${trip.name.replace(/[^a-z0-9]/gi, '_').toLowerCase()}_itinerary.pdf`;
    pdf.save(fileName);

    return Promise.resolve();
  } catch (error) {
    console.error('Error generating PDF:', error);
    throw new Error('Failed to generate PDF. Please try again.');
  }
}

// Alternative method: Convert HTML to PDF (for more styling)
export async function exportHTMLToPDF(elementId: string, filename: string): Promise<void> {
  try {
    const element = document.getElementById(elementId);
    if (!element) {
      throw new Error('Element not found for PDF export');
    }

    const canvas = await html2canvas(element, {
      scale: 2,
      useCORS: true,
      allowTaint: true,
      backgroundColor: '#ffffff'
    });

    const imgData = canvas.toDataURL('image/png');
    const pdf = new jsPDF('p', 'mm', 'a4');
    const imgWidth = 210; // A4 width in mm
    const pageHeight = 297; // A4 height in mm
    const imgHeight = (canvas.height * imgWidth) / canvas.width;
    let heightLeft = imgHeight;
    let position = 0;

    pdf.addImage(imgData, 'PNG', 0, position, imgWidth, imgHeight);
    heightLeft -= pageHeight;

    while (heightLeft >= 0) {
      position = heightLeft - imgHeight;
      pdf.addPage();
      pdf.addImage(imgData, 'PNG', 0, position, imgWidth, imgHeight);
      heightLeft -= pageHeight;
    }

    pdf.save(filename);
    return Promise.resolve();
  } catch (error) {
    console.error('Error generating PDF from HTML:', error);
    throw new Error('Failed to generate PDF from HTML. Please try again.');
  }
}
